# Generated by Django 4.1 on 2022-08-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matabase',
            name='status',
            field=models.CharField(choices=[('d', 'Downloaded'), ('w', 'Watched'), ('r', 'Removed')], help_text='d: Downloaded, w: Watched, r: Removed', max_length=10),
        ),
    ]
