# Generated by Django 4.1 on 2022-08-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matabase', '0002_alter_matabase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matabase',
            name='title',
            field=models.CharField(help_text="Enter movies' title", max_length=200),
        ),
        migrations.AlterField(
            model_name='matabase',
            name='year',
            field=models.CharField(help_text='Enter released year, eg: xxxx', max_length=4),
        ),
    ]
