# Generated by Django 4.1 on 2022-08-11 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matabase', '0004_alter_matabase_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Mag',
        ),
    ]
